### ISSUE TITLE
Vulkan or OpenGL

### ISSUE THREAD

**Issue by stefnotch** [stefnotch/cgue23-cat-to-the-past#2]
Vulkan libraries
- https://github.com/KyleMayes/vulkanalia
- https://github.com/vulkano-rs/vulkano/
- https://github.com/ash-rs/ash

Vulkan tutorials
- https://taidaesal.github.io/vulkano_tutorial/
- https://vulkan-tutorial.com/ is for the basics, see https://github.com/ash-rs/ash/pull/356#issuecomment-759060542
- https://vkguide.dev/
- https://www.intel.com/content/www/us/en/developer/articles/training/api-without-secrets-introduction-to-vulkan-preface.html
- https://zeux.io/2020/02/27/writing-an-efficient-vulkan-renderer/
- https://www.youtube.com/playlist?list=PL0JVLUVCkk-l7CWCn3-cdftR0oajugYvd

Vulkan examples
- https://github.com/SaschaWillems/Vulkan

**Comment by YouSafe** [comment]
Vulkano Tips:
- change branch for up-to-date examples (master branch is not what you want)

**Comment by stefnotch** [comment]
Shaders
https://therealmjp.github.io/posts/shader-permutations-part1/
